spotbugs/sonar-findbugs

- pom.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/test/java/org/sonar/plugins/findbugs/FindSecurityBugsRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsSecurityAuditProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsSecurityMinimalProfileTest.java
- Rules/Profiles/Tests updated
> Update Find Security Bugs plugin to version 1.4.3

- generate_profiles/BuildXmlFiles.groovy
- generate_profiles/out_sonar/EMPTY_DIRECTORY.md
- pom.xml
- Update FindBugs contrib plugin
- Improve the profiles/rules generator
> Update FindBugs contrib plugin

- pom.xml
- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java
Avoid failing the build for test projects or projects with no Java files
> Fix test project failure #33

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
- src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
- src/main/java/org/sonar/plugins/findbugs/resource/DebugExtensionExtractor.java
- src/main/java/org/sonar/plugins/findbugs/resource/SmapParser.java
Fix #42, #43 and #36
#38 is not fix. But additional trace were add to be able to debug the problem.
> Smap improvements and bug fixes

- src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
- src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
- src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
> Fix a bug that fail to map bug instance to outer class #40

- pom.xml
Actual file size is 10_000_000 bytes, so I have updated max and min sizes to 80% and 120% of the size
> Update jar size limits

- README.md
- pom.xml
The readme and plugin description claim the plugin uses FindBugs when
in fact it uses SpotBugs.
> Document SpotBugs usage

- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FbContribRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
Update fb-contrib to 7.0.0, findsecbugs to 1.6.0.
Add few new rules
> fb-contrib 7.0.0 findsecbugs 1.6.0

- src/main/java/org/sonar/plugins/findbugs/xml/FindBugsFilter.java
This commit provides a work around for CVE-2017-7957
http://x-stream.github.io/CVE-2017-7957.html
> Work around CVE-2017-7957

- pom.xml
Same with #90 which used 3.1.0-RC1
> bump up SpotBugs version

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsProfileExporter.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsXmlReportParser.java
- src/main/java/org/sonar/plugins/findbugs/ReportedBug.java
- src/main/java/org/sonar/plugins/findbugs/language/JspSyntaxSensor.java
- src/main/java/org/sonar/plugins/findbugs/language/analyzers/PageCountLines.java
- src/main/java/org/sonar/plugins/findbugs/language/lex/PageLexer.java
- src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
- src/main/java/org/sonar/plugins/findbugs/resource/SmapParser.java
- src/main/java/org/sonar/plugins/findbugs/xml/FindBugsFilter.java
- src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
> Enhancements for 3.5 release

- pom.xml
This will remove broken message in SonarQube plugin page.
> Fix plugin description

- README.md
- generate_profiles/BuildXmlFiles.groovy
- generate_profiles/FsbClassifier.groovy
- generate_profiles/README.md
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-jsp.xml
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityAuditProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
I update the descriptions and the script that generate those.
> Descriptions update

- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-jsp.xml
Spotbugs 3.1.0 RC3 brings android.support.annotations nullability support
Spotbugs 3.1.0 RC3 brings minor dependencies and rule changes
> Use Spotbugs 3.1.0-RC4

- generate_profiles/BuildXmlFiles.groovy
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
Fix this stacktrace due to duplicate rules :
https://groups.google.com/forum/#!topic/sonarqube/cz8E0Ij6oF8
> Fix JSP rules being include both in JSP profiles and Java rules..

- pom.xml
Simply add a `.0` to the version in the `pom.xml`.
> Minor change - set version to 3.6.0

- pom.xml
Updated the SpotBugs to 3.1.0-RC6 and fb-contrib to 7.0.5.sb. I will soon rebuild the quality profiles.
> SpotBugs 3.1.0-RC6 and fb-contrib 7.0.5.sb

- README.md
- generate_profiles/BuildXmlFiles.groovy
- generate_profiles/README.md
- pom.xml
> Use release spotbugs 3.10

- README.md
- pom.xml
This PR closes #152 by using suggested version. It also fixes compatibility table in README.
> Use SNAPSHOT version, to make developing version clear

- .travis.yml
Sorry for my mistake. The `-P` option needs one parameter, to specify profile to enable.
This PR should fix the broken build in master branch.
> Fix wrong command line parameter introduced by 4d815f4e

- .travis.yml
- pom.xml
- src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsTests.java
- src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
- src/test/java/org/sonar/plugins/findbugs/util/TestUtils.java
It seems that current test code cannot work with current LTS and latest version.
This PR reproduces this issue on Travis, by introducing build matrix.
> WIP: Add builds with SonarQube 6.7.1 and 7.0

- .github/issue_template.md
- README.md
- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsConstants.java
- src/main/java/org/sonar/plugins/findbugs/language/Jsp.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java
- src/test/java/org/sonar/plugins/findbugs/rule/FakeRuleFinder.java
Changes
- New configuration "Allow Uncompiled Code"
- Remove Settings API references
- Pushing Github Issue Template (not sure of the result once merge)
I bundle some small refactoring with the PR.
> New configuration "Allow Uncompiled Code"

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsConstants.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java
See #163 
This is the last mini feature I will add before the release of 3.7
> Add configuration for custom paths of existing reports. #163

- README.md
- pom.xml
> prepare for next development

- README.md
- pom.xml
Upgrade SpotBugs to 3.1.5, and fb-contrib to 7.4.2.sb.
> Upgrade dependencies to the latest version

- README.md
- pom.xml
Upgrade find-sec-bugs to the latest version. This will close #155.
> upgrade find-sec-bugs

- README.md
- pom.xml
We've recently released SpotBugs 3.1.6, it might be good timing to release sonar-findbugs.
> Release 3.8

- generate_profiles/BuildXmlFiles.groovy
- generate_profiles/FsbClassifier.groovy
- src/main/java/org/sonar/plugins/findbugs/rules/FbContribRulesDefinition.java
- src/main/java/org/sonar/plugins/findbugs/rules/FindSecurityBugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/test/java/org/sonar/plugins/findbugs/FindSecurityBugsRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityAuditProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
This PR has the same commit with #201, but created from this repository (not forked repository).
This recreation is necessary to pass the SonarQube analysis.
> Same with #201

- README.md
- pom.xml
This PR closes #214 by upgrading SpotBugs to 3.1.8.
> Upgrade SpotBugs to 3.1.8

- src/main/java/org/sonar/plugins/findbugs/FindbugsPlugin.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsProfileExporter.java
- src/main/java/org/sonar/plugins/findbugs/FindbugsProfileImporter.java
- without @ScannerSide the sonar plugin fails to initialize at the time of build
> Issue #218 Added missing annotations

- README.md
- RELEASE_PROCEDURE.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/test/java/org/sonar/plugins/findbugs/FindbugsProfileImporterTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
This release contains following fixes:
* Bump up SpotBugs to 3.1.8, for better Java 12 support #217 and fixing SpotBugs bugs #212
* SonarQube compatibility 7.4 #218
> Release 3.9 with updated xml

- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
Upgrade SpotBugs to 3.1.10 that includes better Java 11 support with ASM7.
https://github.com/spotbugs/spotbugs/releases/tag/3.1.10
> bump up SpotBugs to 3.1.10

- README.md
* Add 3.9.2 to README
* Replace Minimum SQ version with Supported SQ verison
> Tell maximum supported version in README

- README.md
- pom.xml
This version closes #248 by #250.
> Release 3.9.3 for user of SonarQube LTS 

- .travis.yml
- src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
this is a replication of https://github.com/spotbugs/sonar-findbugs/pull/265 to support the current LTS branch
> Support latest sonar-java

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/smoke-test/smoke-test.sh
This PR closes #278.
I've confirmed that [our smoke-test reproduces this problem](https://travis-ci.org/spotbugs/sonar-findbugs/jobs/555567755) and [this fix removes the target message in build log](https://travis-ci.org/spotbugs/sonar-findbugs/jobs/558766717).
> Solve the warning from SonarQube 7.9

- pom.xml
The old versions are already outdated and not supported, refer:
https://github.com/SonarSource/sonar-update-center-properties/pull/102#issuecomment-605668947
> Bump up SQ and its Java plugin to the latest LTS

- src/smoke-test/sonarqube-client
- src/smoke-test/sonarqube-latest
* bump up Maven for smoke-test to the latest 3.6.3
* bump up SQ for smoke-test to the latest 8.2
> Update Maven and SQ for the Smoke Test

- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/test/java/org/sonar/plugins/findbugs/FindbugsProfileImporterTest.java
Updated spotbugs 4.1.2
updated dependencies
> Release 4.0.1

- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityAuditProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
> Release 4.0.2

- .github/workflows/release.yml
- RELEASE_PROCEDURE.md
- pom.xml
Release next version with a security fix #347.
Also try to apply the [release automation for SonarQube plugin](https://github.com/KengoTODA/sonar-update-center-action/).
> Release 4.0.3

- .github/workflows/build.yml
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/test/java/org/sonar/plugins/findbugs/FindbugsProfileImporterTest.java
> Issue #376 bump up SpotBugs to 4.4.0

- .github/workflows/build.yml
- README.md
* Updated the SpotBugs versions in the doc and the plugin description
* Updated the rules count
* Updated the minimum SQ supported version for the marketplace (see https://github.com/SonarSource/sonar-update-center-properties/pull/247#discussion_r736815447)
> docs, ci: updated the SpotBugs version, the rules count

- README.md
- pom.xml
This release includes the following changes:
- Fix of the crash on server startup: https://github.com/spotbugs/sonar-findbugs/issues/387
- Upgrade to SpotBugs 4.5.0
- Deprecate some rules: https://github.com/spotbugs/sonar-findbugs/issues/304
> Release 4.0.5

- pom.xml
- src/test/java/org/sonar/plugins/findbugs/FbContribRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/findbugs/FindSecurityBugsRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsCategoryTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsProfileExporterTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsProfileImporterTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsRulesDefinitionTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsTests.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsVersionTest.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsXmlReportParserTest.java
- src/test/java/org/sonar/plugins/findbugs/it/FBContribIT.java
- src/test/java/org/sonar/plugins/findbugs/it/FindbugsIT.java
- src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsContribProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityAuditProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityJspProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
- src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
- src/test/java/org/sonar/plugins/findbugs/resource/DebugExtensionExtractorTest.java
- src/test/java/org/sonar/plugins/findbugs/util/JupiterLogTester.java
- JUnit upgraded from 4 to 5
- Mockito upgraded from 3 to 4
- Fest upgraded to AssertJ
> test: Upgraded test dependencies

- .github/workflows/build.yml
- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
> deps: bump SpotBugs to 4.5.2

- src/test/java/org/sonar/plugins/findbugs/it/FindSecBugsJspIT.java
- src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java
- src/test/resources/projects/jspc-jetty/pom.xml
- src/test/resources/projects/jspc-jetty/src/main/webapp/WEB-INF/jsp/pages/page1/page1.jsp
- src/test/resources/projects/jspc-jetty/src/main/webapp/WEB-INF/jsp/pages/page2/page2.jsp
- src/test/resources/projects/jspc-jetty/src/main/webapp/WEB-INF/web.xml
- src/test/resources/projects/jspc-sling/pom.xml
- src/test/resources/projects/jspc-sling/src/main/scripts/index.jsp
- src/test/resources/projects/jspc-sling/src/main/webapp/WEB-INF/web.xml
Check that pre compiled JSP files are analyzed before fixing issue #275
> test: Add some integration tests for JSP analysis

- .github/workflows/build.yml
- README.md
- generate_profiles/BuildXmlFiles.groovy
- generate_profiles/FsbClassifier.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindSecurityBugsRulesDefinition.java
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-audit.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-security-minimal.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
- src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
- Upgraded SpotBugs to 4.6.0
- Upgraded FindSecBugs to 1.12.0
- Updated the rules metadata
- Updated the rules count
> Upgrade SpotBugs to 4.6.0 and FindSecBugs to 1.12.0

- .github/workflows/build.yml
- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- Updated plugin description
- Updated rules metadata
- Updated rules count
> Upgrade SpotBugs to 4.7.0

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
- src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java
Added diagnostic details in case there was no compiled code
> feature: clearer error message

- .github/workflows/build.yml
- README.md
- generate_profiles/BuildXmlFiles.groovy
- pom.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- Updated version in pom, readme and groovy script
- Adjusted the BuildXmlFiles.groovy to run on JDK 17
- Generated updated rules metadata
> deps: bump spotbugs to 4.7.2

- pom.xml
> Upgrade to asm 9.5 in order to support Java 21 (#733)

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
As suggested by @himanshu-pathak in #1023
> Report found languages when failing on missing compiled .class

- README.md
- pom.xml
To be merged, not squashed, so the two commits remain and the first one can trigger the release workflow
> Release 4.2.10

- .github/actions/sonar-update-center/.github/workflows/integrationTest.yml
- .github/workflows/build.yml
- .github/workflows/sonar-update-center.yml
This reverts commit 6f52d0496b58804415548af3e37f7eb516e6678e.
> Revert "Add env for github token (#1228)"

- src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
> Fix the extension check for kts files

- README.md
- generate_profiles/BuildXmlFiles.groovy
- src/main/java/org/sonar/plugins/findbugs/rules/FbContribRulesDefinition.java
- src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml
- src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml
- src/test/java/org/sonar/plugins/findbugs/it/MultiModuleIT.java
> deps: upgrade sb contrib to 7.6.13
