spotbugs/sonar-findbugs

src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java, src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java, src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
See issue #51 ...
I tried to generally preserve original behaviour. But if given class is a suffix for some known InputFile then take that one.
=> #51: Find issues in nonstandard source file layouts

src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
It makes finding a subproject without compiled sources in a build with
multiple subprojects much easier.
Fixes #65.
=> [#65] Add project path to error messages

src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
Use javaResourceLocator.findSourceFileKeyByClassName instead of classpath
iteration to locate source file.
(Note that this PR doesn't bump the version number in any way)
=> [#77] Change bytecode to source mapping

pom.xml, src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java
I'm not sure when you'll replace FindBugs with SpotBugs, hope that this PR helps you to have a try.
This change makes sonar-findbugs depending on SpotBugs 3.1.0-RC1
which does not support Java7. See changelog for detailed difference:
https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#310-rc1-2017feb21
Note that this change is based on MichaelHai's change which is proposed at:
https://github.com/spotbugs/spotbugs/issues/136
=> FYI: Replace FindBugs 3.0.1 with SpotBugs 3.1.0-RC1

generate_profiles/BuildXmlFiles.groovy, src/main/java/org/sonar/plugins/findbugs/rules/FbContribRulesDefinition.java, src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java, src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml, src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml, src/test/java/org/sonar/plugins/findbugs/FbContribRulesDefinitionTest.java, src/test/java/org/sonar/plugins/findbugs/FindbugsRulesDefinitionTest.java
Experimental rules are currently not registered. This means that people
than not test test them. This leads to issues like #85.
It is important to note that this commit does not enable experimental
rules by default. They are still missing from all quality profiles.
If people want to test them they still have to create their own quality
profile with experimental rules.
This adds the following experimental rules
- SKIPPED_CLASS_TOO_BIG
- DP_DO_INSIDE_DO_PRIVILEDGED
- RCN_REDUNDANT_CHECKED_NULL_COMPARISON
- OBL_UNSATISFIED_OBLIGATION
- OBL_UNSATISFIED_OBLIGATION_EXCEPTION_EDGE
- LG_LOST_LOGGER_DUE_TO_WEAK_REFERENCE
This adds the following experimental contrib rules
- LO_EMBEDDED_SIMPLE_STRING_FORMAT_IN_FORMAT_STRING
- IOI_USE_OF_FILE_STREAM_CONSTRUCTORS
=> Register experimental rules

README.md
After #90 and #97 the version information in the README was outdated.
To the exact the following versions were outdated:
- Embedded Findbugs version
- Embedded Findsecbugs version
- Embedded FB-Contrib version
=> Update version information

generate_profiles/BuildXmlFiles.groovy, src/main/java/org/sonar/plugins/findbugs/rules/FindSecurityBugsRulesDefinition.java, src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
In find-sec-bugs v1.6, two new BugPatterns were added by https://github.com/find-sec-bugs/find-sec-bugs/pull/261
But now sonar-findbugs doesn't have them in `rules-findsecbugs.xml` so let's add to enable these rules even in SonarQube.
I added these rules to `criticalBugs`, however another level might be better to use.
Please point the right level if necessary.
=> add two rules which was introduced at find-sec-bugs v1.6

pom.xml
There is a BCEL issue that was fixed in fbcontrib 7.0.3:
https://github.com/mebigfatguy/fb-contrib/issues/205
It would be nice to upgrade this dependency in next sonar-findbugs release (3.6.0?).
=> Updated fbcontrib dependency

README.md
This kind of solves #119 by adding description for configuration parameters to README
I had to inspect source code to find these parameters out. It was not clear at all that these parameters exist
=> Describe configuration in README.md

pom.xml
fb-contrib dependency is different depending on wether you are using findbugs(7.0.3) or in this case, SpotBugs (7.0.3.sb).
The current Readme for fb-contrib states this explicitly in the beginning of the readme: https://github.com/mebigfatguy/fb-contrib
So, Setting dependency to fb-contrib 7.0.3.sb.
=> Updating fb-contrib dependency

README.md, src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
Skip module-info.class from Java9 Jigsaw which cause problem in the current SpotBugs release.
=> Skip module-info.class from Java9 Jigsaw 

.travis.yml, README.md, pom.xml
1. Use the latest SpotBugs
2. Stop signing jar files in post-merge build, to avoid STABLE deployment
=> Minor changes

README.md, pom.xml
This change will close #159. I've confirmed that local `mvn clean verify` can pass without error.
=> upgrade fb-contrib to the latest version

src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
Hello,
I propose a quick fix of the issue:
https://github.com/spotbugs/sonar-findbugs/issues/148
=> #148 Excluded Java Server Pages (JSPs) from Java source files to fix failure when analyzing module with non-compiled JSPs

README.md
I fixed the link to the SonarJava plugin in the readme file. The http://docs.sonarqube.org/display/PLUG/Java+Plugin link wasn't working anymore.
=> Fixed link to the SonarJava plugin in the readme file

pom.xml
I added **project.build.sourceEncoding** property to the pom.xml file to fix maven warning:
[WARNING] File encoding has not been set, using platform encoding Cp1250, i.e. build is platform dependent!
I believe it's a good practise to specify the encoding in POM files.
=> Fixed warning about platform dependent build

.travis.yml
I found that now [Sonar Cloud](https://sonarcloud.io/dashboard?id=com.github.spotbugs%3Asonar-findbugs-plugin) has no analysis result, and it comes from my wrong `.travis.yml`.
This PR fixes this problem.
=> Run sonar if $SONAR_VERSION is latest LTS

README.md, pom.xml
This version includes BCEL & ASM update that makes Java 9/10 support better.
=> update SpotBugs to 3.1.3

README.md
refer https://about.sonarcloud.io/news/2018/02/05/new-project-badges.html
=> replace old badge with new one

.travis.yml
by this `if`, we limit sonarqube analysis only in following cases:
1. pull requests that uses the spotbugs organization as HEAD branch, or
2. other type of build that runs in the spotbugs organization
=> stop running sonarqube analysis on the PR made from forked repo

src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java, src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java, src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
BatchExtension has been removed in SonarQube 7.3 ( https://jira.sonarsource.com/browse/SONAR-10138 ). BatchExtension replaced for the SonarQube 7.3 compatibility #204
=> Replace BatchExtension for SQ 7.3 compatibility #204 

.travis.yml, pom.xml, src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java
Change ExtensionPoint annotation to ScannerSide (class ByteCodeResourceLocator)
This seems to be the last element missing to complete the migration to SonarQube 7.3.
I have added the compatibility testing for 7.3 in the travis.yml. https://github.com/spotbugs/sonar-findbugs/pull/209/commits/6e6e48babbff90b6c6714ae82c57401a1be4056f
=> SonarQube 7.3 (latest) compatibility

README.md, pom.xml
This PR firstly reverts three commits that was introduced in #198, to reproduce the revision that uses 3.8.0-SNAPSHOT with sonar-java 5.1.0.13090. After that, this PR tries to release 3.8.0 again.
=> Retry to release 3.8

README.md, pom.xml
Java 11 was released on September 25th and is the new LTS version.
At this point sonar-findbugs is not able to analyse projects built with Java 11, but fortunately SpotBugs has added proper support in release 3.1.7 (see [#750](https://github.com/spotbugs/spotbugs/pull/750)). This pull request simply bumps up the dependency version used by sonar-findbugs.
Note that I have built an artifact based on this fork and have uploaded it to our SonarQube server, and I can confirm that our Java 11 projects are now happily being analysed. 👍
=> Update SpotBugs to 3.1.7

.travis.yml, README.md, pom.xml
sonar-java has released 5.2.0 that supports SonarQube 6.7. See:
- SonarSource/sslr-squid-bridge@d481fef
- SonarSource/sonar-java@0ca6061
In other words, sonar-java 5.1 does not support latest LTS 6.7.x. To support SonarQube 6.7.x, sonar-findbugs should depend on sonar-java 5.2.0 or later.
Also, SonarQube released 6.7.5 and 7.4, so use them in CI build. I'll try to fix 7.4 compatibility problem by another PR.
=> Update sonar-java to support SonarQube LTS 6.7 correctly

.dockerignore, .travis.yml, pom.xml, src/smoke-test/docker-compose.yml, src/smoke-test/run.sh, src/smoke-test/smoke-test.sh, src/smoke-test/sonarqube-client, src/smoke-test/sonarqube-latest, src/smoke-test/sonarqube-lts
As described in #225, `sonar-channel` and `commons-io` has been removed from SonarQube plugin API 7.4. This is why [the build with SonarQube plugin API 7.4 is failing](https://travis-ci.org/spotbugs/sonar-findbugs/jobs/452346817), and sonar-findbugs 3.9 lacks compatibility with SonarQube 7.4.
In this PR, I reproduce reported issue #226 by smoke test, and fix it by packaging `sonar-channel` and `commons-io` into sonar-findbugs. We need to use `maven-shade-plugin` because `sonar-packaging-maven-plugin` does not package these two libraries. Here is message:
> [WARNING] commons-io:commons-io:jar:2.6:compile is provided by SonarQube plugin API and will not be packaged in your plugin
> [WARNING] org.codehaus.sonar:sonar-channel:jar:4.2:compile is provided by SonarQube plugin API and will not be …
=> Package sonar-channel that is removed from SonarQube plugin API 7.4

src/smoke-test/docker-compose.yml
On Travis CI, it is possible that docker image fails to make directory
under .m2 file due to permission problem. To avoid this issue, stop
sharing local repository. It may make build elapsed time londer.
I'm not sure why this failure didn't occur in PR and topic branch, it could be non-documented behabiour of Travis.
refs #231
=> Make smoke-test stable even in master branch

.travis.yml, src/smoke-test/sonarqube-lts
Bump up the SonarQube version that is used in test.
This change doesn't affect the released artifact; the `MANIFEST.MF` file in jar file keeps using `Sonar-Version: 6.7.1`.
=> Bump up SonarQube LTS to 6.7.6

.travis.yml, src/smoke-test/sonarqube-latest, src/test/java/org/sonar/plugins/findbugs/rule/SimpleActiveRule.java
[The docker image for 7.5](https://hub.docker.com/_/sonarqube/) is not available, so we do not update files in `src/smoke-test` in this timing.
I've confirmed that SonarQube 7.5 community edition is packaged with sonar-java 5.9.2.16552.
=> build and test with SonarQube 7.5

.travis.yml, README.md, pom.xml, src/smoke-test/sonarqube-latest
This PR is to release sonar-findbugs 3.10 that supports SonarQube 7.6 *only*. This version does not support SonarQube 7.5 and older, see https://github.com/spotbugs/sonar-findbugs/pull/242#issuecomment-458971587 and https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/213#issuecomment-459016381 for detail.
For LTS users, #243 will release sonar-findbugs 3.9.2.
This version also introduces the latest SpotBugs 3.1.11.
=> Release 3.10 for sonarqube 7.6

.travis.yml, README.md, pom.xml
According to https://github.com/spotbugs/sonar-findbugs/pull/242#issuecomment-458971587, current `master` branch does not support SonarQube 6.7.x LTS. Then before release 3.10, let's release 3.9.2 that can work with  SonarQube 6.7.x LTS.
note: According to that comment, this `release-for-lts` branch could be necessary just for several coming months.
> We also have another LTS version planned in a few months.
=> Release 3.9.2

src/main/java/org/sonar/plugins/findbugs/resource/DebugExtensionExtractor.java
This PR fixes #248. It is necessary to release 2.9.3 after we merge this fix.
It is also necessary to merge `release-for-lts` branch to `master`... this operation will be needless after SonarSource releases next LTS in near future (hopefully).
=> Specify the latest ASM version

.travis.yml
The `github_token` is deprecated, and it enforces SonarQube to use old feature that is removed from SonarCloud. Instead, we need to set GitHub token in the config page in the SonarCloud.
refs: https://docs.travis-ci.com/user/sonarcloud/
=> chore: stop depending on old configuration

README.md, pom.xml, src/main/java/org/sonar/plugins/findbugs/resource/DebugExtensionExtractor.java
These changes are applied to the branch for LTS support. We also need them even in `master` branch.
[Full Changelog](https://github.com/spotbugs/sonar-findbugs/compare/3.10.0...reflect-changes-in-lts-branch)
* Bump up find-sec-bugs to 1.9.0
* Bump up spotbugs to 3.1.12
* Incompatibility with sonar-java 5.12 #263
* Fails when analyzing Java 11 source code with nested class #248
=> Reflect changes in lts branch, and release 3.11.0

.travis.yml
Current setting runs `mvn deploy` in PR if the base branch is `master`.
By checking `type` we avoid this unsafe release.
According to [official doc](https://docs.travis-ci.com/user/conditions-v1), `branch` is the base branch name for PR. Then in PR for `master` branch, the `if` condition for deployment is fulfilled so unapproved change can be released to Sonatype Nexus Maven repository.
=> Do not release in PR

.travis.yml, src/smoke-test/sonarqube-latest, src/smoke-test/sonarqube-lts
Smoke-test in master branch is broken, maybe caused by the change in `sonarqube` docker image, and it's blocker for #283. This PR will fix this broken smoke-test.
=> test: Fix smoke test

pom.xml
This PR will handle:
1. Fix a vulnerability `CVE-2019-10173 `, and
2. Release v3.11.1 to Maven Central.
=> Release 3.11.1 retry

pom.xml
refs #337 and http://x-stream.github.io/CVE-2020-26217.html
=> Bump up xstream to the latest version

src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml, src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml, src/main/resources/org/sonar/plugins/findbugs/rules-findsecbugs.xml
Fixed invalid html (missing closing tags) in rules description.
=> Fix html descriptions

.github/workflows/build.yml
The [build in GitHub Actions](https://github.com/spotbugs/sonar-findbugs/runs/1647267180) is failed, because I simply forgot checking out the Git repo... 😩
I'm sorry, here is fix for the problem. refs #350
=> Checkout the repo before the deployment

README.md
GitHub changed the URL of workflow status badge.
We need to change `README.md` to keep it updated.
=> docs: fix the build status badge

generate_profiles/BuildXmlFiles.groovy
When generating rules metadata, the Groovy script uses the system encoding and caracters such as the French 'é' in Grégoire are incorrectly written. When trying to build with these XML files, the maven resources plugin then fails because there are invalid characters.
=> Explicitly use UTF-8 so we don't default to the system encoding

.github/workflows/build.yml, .github/workflows/sonarqube.yml
This PR makes SonarQube running properly even in the PR from forked repos.
refs https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
Also replace the AdoptOpenJDK with Adoptium, because [AdoptOpenJDK will not be updated](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/) soon.
=> Run SonarQube in pull_request_target

README.md
The readme page was still for version 4.0.3 of the plugin, I've included the newer versions and added that older versions were not compatible with SQ 9
=> Updated the rules count and the compatibility table

.github/workflows/sonarqube.yml
Follow up for #380. That change made SQ running in PR from the forked repo, but we have two problems:
1. [Analysis runs on the BASE](https://github.com/spotbugs/sonar-findbugs/pull/382/checks#step:2:489) but it should use HEAD
2. Analysis result wasn't reported on its source PR like #382
Also, I found that SQ didn't run on a tag but it's necessary to [request a release at SQ forum](https://community.sonarsource.com/t/new-release-sonar-findbugs-4-0-4/48718). This PR will tackle these three problems.
=> Resolve several problems around SonarQube analysis

.github/workflows/sonarqube.yml
Currently the build in PR is broken, see [this workflow run for example](https://github.com/spotbugs/sonar-findbugs/runs/3948483294?check_suite_focus=true#step:2:498).
>   Error: A branch or tag with the name 'add-deprecated-jsp-rule-key' could not be found
It is because `github.event.pull_request.head.ref` points the branch name, which does not exist in this repo. It exists in another forked repository.
To solve this issue, we can checkout the branch `refs/pull/${{ github.event.pull_request.number }}/merge` [which is the default branch to checkout for `pull_request` event](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request).
=> ci: checkout the merge commit for PR_target event

src/main/java/org/sonar/plugins/findbugs/FindbugsProfileImporter.java, src/main/java/org/sonar/plugins/findbugs/rules/FindSecurityBugsJspRulesDefinition.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityJspProfileTest.java
Between version 3.3 and 3.4 of the plugin rules XSS_JSP_PRINT and XSS_REQUEST_PARAMETER_TO_JSP_WRITER have been moved from the Java findsecbugs repository to the JSP findsecbugs-jsp repository.
When a rule key is modified the plugin should apparently declare it's "deprecated key(s)" to let SonarQube know, see: https://javadocs.sonarsource.org/7.1/apidocs/org/sonar/api/server/rule/RulesDefinition.Rule.html#deprecatedRuleKeys--
The database was left in an apparently inconsistent state for SQ installations where the plugin had been upgraded from <= 3.3 to >= 3.4
Then when the API used to load profiles was changed in https://github.com/spotbugs/sonar-findbugs/pull/369 (to make the plugin compatible with SQ 9) the server crashed on startup with error: `BadRequestException: java rule …
=> Issue #387 Add deprecated jsp rule key

generate_profiles/BuildXmlFiles.groovy, pom.xml, src/main/java/org/sonar/plugins/findbugs/rules/FindbugsRulesDefinition.java, src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-and-fb-contrib.xml, src/main/resources/org/sonar/plugins/findbugs/profile-findbugs-only.xml, src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
- Upgraded SpotBugs to 4.5.0
- Modified the rules metadata accordingly
- Modified the rules count
=> bump up SpotBugs to 4.5.0

.github/workflows/sonarqube.yml
Currently the build tries to run a SonarQube analysis but this fails when running on a forked repo, because it does not have access to the account secrets.
=> ci: skip the SonarQube analysis on forked repos

.github/workflows/sonar-update-center.yml
Add a [missing parameter to support sub project](https://github.com/actions/setup-node/tree/360ab8b75b056fc18d368ee27a78d34e29c0b2d9#caching-packages-dependencies), which makes #405 and other builds failed.
Note that this workflow file defines a workflow triggered by a `pull_request_target` event, so we need to merge the change first to fix the problem. In other words, the related GitHub Check will fail even in this PR. It is because `pull_request_target` always use the workflow definition in the default branch.
=> ci: add missing param to cache dependency in sub project

generate_profiles/deprecated_rules/sb-contrib/SPP_TOSTRING_ON_STRING.json, generate_profiles/deprecated_rules/sb-contrib/SPP_USE_BIGDECIMAL_STRING_CTOR.json, src/main/resources/org/sonar/plugins/findbugs/rules-fbcontrib.xml
I made a mistake when typing the replacements and two of them were swapped.
This PR fixes the rules metadata for these two deprecated rules.
=> Fixed swapped replacement for deprecated rules

.github/workflows/build.yml
* Currently the deploy tries to run on forked repos and fails because it does not have the secrets
* Cache the maven dependencies to speed up the build
=> ci: skip the deploy when running on a forked repo

.github/workflows/sonarqube.yml
- Build against the previous SonarQube LTS (the plugin does not work with 7.6)
- Cache maven resources to speed up the build
=> build: sonarqube analysis fixes

src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java
File.length() is unspecified for directories so we test if the existing report file is a directory.
=> fix: issue #434 handle the case when the existing report is a directory

.github/workflows/build.yml, README.md, generate_profiles/BuildXmlFiles.groovy, pom.xml
SpotBugs 4.5.3 surfaced a bug in FindSecBugs, revert to 4.5.2 until a new version with the fix is release, see: https://github.com/find-sec-bugs/find-sec-bugs/issues/668
=> Revert to SpotBugs 4.5.2

src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsContribProfileTest.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsProfileTest.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsScalaProfileTest.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityAuditProfileTest.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityJspProfileTest.java, src/test/java/org/sonar/plugins/findbugs/profiles/FindbugsSecurityMinimalProfileTest.java
Test that we can upgrade from 4.0.6 and that profiles only contain rules for the relevant language
=> test: IT reproducing issue #516 and UT for languages

pom.xml
Need to remove the plugin dependency from the manifest of the plugin because the sonar-java is no longer part of the marketplace (per SonarSource request)
=> deps: remove sonar-java plugin dependency

.github/workflows/build.yml, README.md, pom.xml
We need to remove the plugin dependency to sonar-java: https://community.sonarsource.com/t/new-release-sonar-findbugs-plugin-4-1-3/61969/6
=> Release 4.1.4

src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
Add the classpath entries in case javaResourceLocator.classFilesToAnalyze() returned an empty list
=> fix: issue #559

.github/workflows/build.yml, .github/workflows/sonarqube.yml, pom.xml, src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java
With 9.5 SonarSource announced that "The sonar-plugin-api is now released independently" and there's a 9.6 version of the API already.
Decouple the properties for the sonar server version and the sonar plugin API version
=> Test against sonarqube 9.5

src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java, src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
Path.of() was added in Java 11. Even if the build runs on Java 11 the
project is on Java 8
=> test: remove java 11 usage in unit tests

src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java, src/main/java/org/sonar/plugins/findbugs/FindbugsVersion.java, src/main/resources/org/sonar/plugins/findbugs/findbugs-plugin.properties
Many users don't know the version they are using because they do not have access to the SonarQube server administration page. Log the version so we don't waste time while they ask they ask their administrator
=> feature: log the plugin version

src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java
We have copied the plugin jar in the project's build directory. Now we need to close the classloaders pointing to that jar so we do not prevent the deletion of the build folder.
Fixes #128
=> fix: close plugins at the end of the analysis

.github/workflows/build.yml, pom.xml, src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java
Since 9.8 the instance created for integration tests has the permission to run an analysis disabled by default, updated orchestrator so we can enable the permission
=> tests: Run the integrations tests against SQ 9.8

src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java
Since SpotBugs 4.7.3 and https://github.com/spotbugs/spotbugs/pull/2123 it is no longer necessary to set the security manager6
=> fix: stop updating the security manager

README.md, src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java, src/main/java/org/sonar/plugins/findbugs/FindbugsConstants.java, src/main/java/org/sonar/plugins/findbugs/FindbugsPlugin.java, src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java, src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java
Tests are analyzed by default, added an option so this can be disabled. For some users this should be simpler than adding an exclude filter
=> feature: new option to analyze tests

pom.xml
Upgrade xstream to solve CVE-2022-41966
=> deps: upgrade xstream to 1.4.20

.github/actions/sonar-update-center/package-lock.json, .github/actions/sonar-update-center/package.json
Prettier needs eslint-plugin-prettier 4 which is a transitive dependency of eslint-plugin-github so upgrade both a the same time
=> deps: bump prettier to 3.0.3

pom.xml
Now that SpotBugs is upgraded to 4.8.1 we can revert to using the transient ASM dependency version (i.e. 9.6)
=> deps: revert to using the ASM version provided by SpotBugs

src/main/java/org/sonar/plugins/findbugs/AnalysisResult.java, src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java, src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java, src/test/java/org/sonar/plugins/findbugs/FindbugsExecutorTest.java, src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java
Analysis errors caught during by SpotBugs are logged by the sensor but not reported on the Sonarqube server.
Collect the errors and report them in the sensor context so they are reflected on the server.
=> Report analysis errors

src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java
In SonarQube the plugin version is only available in the admin pages
=> Add the plugin version to the analysis error messages

pom.xml, src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java
See https://community.sonarsource.com/t/the-sonarscanners-download-only-required-3rd-party-plugins/108156
Fixes #957
=> Package with the new DownloadOnlyWhenRequired manifest entry

.github/actions/sonar-update-center/.github/workflows/integrationTest.yml
`set-output` is deprecated, see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> build: replaced deprecated set-output

.github/workflows/build.yml, .github/workflows/sonarqube.yml, README.md, pom.xml, src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java, src/main/java/org/sonar/plugins/findbugs/FindbugsPlugin.java, src/main/java/org/sonar/plugins/findbugs/FindbugsSensor.java, src/main/java/org/sonar/plugins/findbugs/classpath/ClasspathLocator.java, src/main/java/org/sonar/plugins/findbugs/classpath/DefaultClasspathLocator.java, src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java, src/test/java/org/sonar/plugins/findbugs/FindbugsConfigurationTest.java, src/test/java/org/sonar/plugins/findbugs/FindbugsPluginTest.java, src/test/java/org/sonar/plugins/findbugs/FindbugsSensorTest.java, src/test/java/org/sonar/plugins/findbugs/it/FindSecBugsJspIT.java, src/test/java/org/sonar/plugins/findbugs/it/FindbugsTestSuite.java, src/test/java/org/sonar/plugins/findbugs/it/ScalaIT.java, src/test/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocatorTest.java
Since Sonarqube 10.6 the plugin can no longer reliably depend on the built-in sonar-java plugin.
We are using it to get the project classpath and list the .class files we want to analyze.
Instead bundle (shade) the plugin and the other dependencies so we can use it.
Since we are not running the sonar-java plugin and since `classFilesToAnalyze()` was populated as a side effect of sonar-java running, we need to get the class files ourselves. This will change the behaviour because now we get all the class files from the binary dirs, so we might analyze files that were previously marked as excluded.
=> Bundle sonar-java and dependencies

.github/workflows/build.yml
sonar-java-plugin requires JDK 17
=> Use JDK 17 to deploy

src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java
kts files are typically not compiled into a .class file, ignore them when looking for uncompiled projects
This should fix #1037
=> Ignore .kts file when looking for sources

pom.xml
Hello @hazendaz, even though the renovate PR might pass tests we must be careful when updating dependencies because we need compatibility with various versions of SonarQube.
This should fix #1183
=> deps: revert to the plugin API 9.14.0.375 for SonarQube 9.9 compat.

.github/workflows/build.yml
Remove the plugin-api from the build parameters so we run the integration tests using the same version as the published plugin. This should catch incompatibility errors such as #1183
=> Test against SonarQube 25.3 and 9.9.9

.github/actions/sonar-update-center/.github/workflows/integrationTest.yml, .github/workflows/build.yml, .github/workflows/sonar-update-center.yml, README.md, generate_profiles/BuildXmlFiles.groovy, pom.xml
There was no update to the rules metadata this time around
=> Upgrade SpotBugs to 4.9.3

.mvn/extensions.xml, pom.xml
for maven clean, maven had a bug in 3.4.1 that blocked checkout folder on release from being deleted (any read only file).  Instead of fixing the issue, they added a flag so the world must fix it.
=> Update profiler to 3.3 and restore maven clean plugin 3.4.0 support

README.md, generate_profiles/BuildXmlFiles.groovy, pom.xml, src/main/resources/org/sonar/plugins/findbugs/rules-findbugs.xml
SpotBugs [4.9.5](https://github.com/spotbugs/spotbugs/releases/tag/4.9.5) is released, this PR on top of https://github.com/spotbugs/sonar-findbugs/pull/1320 updates the readme and the `generate_profiles/BuildXmlFiles.groovy` file, and ran the groovy file resulting in the change in `rules-findbugs.xml`.
=> Upgrade SpotBugs to 4.9.5
